"""Add google_drive_enabled column

Revision ID: 5ff3f881417b
Revises: 
Create Date: 2025-03-10 13:43:08.153552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff3f881417b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('bates_prefix')

    with op.batch_alter_table('document_tags', schema=None) as batch_op:
        batch_op.drop_column('added_at')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('document_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bates_prefix', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
